global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'tradingbot'
    static_configs:
      - targets: ['metrics-exporter:9122']
    scrape_interval: 1s
